---
- hosts: all
  become: yes
  roles:
    - role: router_base
    - role: vlan_nic
      vlan_nic_vlanid: "{{ vlanid.ebgp }}"
      vlan_nic_ip4: "{{ own.bgprt[0].ebgp_ip }}"
    - role: vlan_nic
      vlan_nic_vlanid: "{{ vlanid.ospf }}"
      vlan_nic_ip4: "{{ own.bgprt[0].ospf_ip }}"
    - role: bgp_router
    - role: ospf_router
  vars:
    bgp_router_self_as_number: "{{ own.as_number }}"
    bgp_router_opponent_as_number: "{{ isp.as_number }}"
    bgp_router_self_id: "{{ own.bgprt[0].bgp_router_id }}"
    bgp_router_opponent_id: "{{ isp.bgprt[0].bgp_router_id }}"
    bgp_router_assigned_network: "{{ own.assigned_network }}"
    ospf_router_self_id: "{{ own.bgprt[0].ospf_router_id }}"
    ospf_router_assigned_network: "{{ own.assigned_network }}"
    ospf_router_loopback_interface_ip4: "{{ own.bgprt[0].ospf_router_id }}"
    ospf_router_host_name: "own-bgprt01"
    vlan_nic_ifname: "{{ vlan_ifname }}"
